H-HEY LASYA? #0 #3 #- #2 #0,0,-,-
OH PRABHU! WHAT'S UP? #1 #0
UHM... S-SO REMEMBER YOU WERE T-TELLING ME ABOUT HOW YOU WERE SUPER S-SCARED FOR THE EXAM? #0 #3
YEAH, I AM! I HEARD IT'S GOING TO BE REALLY HARD THIS TIME... WHY, WHAT'S UP? #1 #0
W-WELL, S-SINCE YOU T-TOLD ME YOU WERE REALLY S-STRESSED ABOUT THE EXAM, W-WELL, T-TO HELP YOU, UHM... #0 #2
UHH... PRABHU, ARE YOU OKAY? #1 #0
W-WELL, I JUST WENT INTO THE T-TEACHERS' DEPARTMENT AND S-STOLE THE EXAM P-PAPER F-FOR YOU! #0 #3
... #1 #0 #- #3
..... #0 #2
....... #1 #0
......... #0 #2
........... #1 #0
........................................................... #0 #2
OH MY GOD THAT'S SO SWEET OF YOU! THANK YOU! #1 #0 #0 #4
W-WELL YOU'RE WELCOME! (SHE CALLED ME SWEET!?!?!?) #0 #1 //overjoyed
THIS WILL BE REALLY HELPFUL FOR MY BOYFRIEND! #1 #0 #- #- #0,5,-,-
(WAIT. BOYFRIEND?) #0 #6 #- #- #2,1,33,2.5 #0,6,-,-
THANKS FOR THE HELP IDIOT #2 #0
(HE'S HER BOYFRIEND???? THE GUY WHO GOT AN YEAR BACK BECAUSE HE FAILED A SUBJECT???????) #0 #6
GOOD JOB MAKING HIM STEAL THE PAPER FOR ME LASYA #2 #0 #- #- #2,3,-,- #1,2,-,- #0,5,-,- 
COME NOW LET'S GO TO MY HOUSE FOR "GROUP STUDIES" #2 #0
HEHE, CAN'T WAIT! #1 #0 #- #- #2,0,39,4 #1,0,39,4
... #0 #6 #- #- #0,4,-,-
