H-HEY LASYA? #0 #7 #- #3 #0,0,-,-
OH PRABHU! WHAT'S UP? #1 #3
UHM... S-SO REMEMBER YOU WERE T-TELLING ME ABOUT HOW YOU WERE SUPER S-SCARED FOR THE EXAM? #0 #7
YEAH, I AM! I HEARD IT'S GOING TO BE REALLY HARD THIS TIME... WHY, WHAT'S UP? #1 #2
W-WELL, S-SINCE YOU T-TOLD ME YOU WERE REALLY S-STRESSED ABOUT THE EXAM, W-WELL, T-TO HELP YOU, UHM... #0 #7
UHH... PRABHU, ARE YOU OKAY? #1 #3
W-WELL, I JUST WENT INTO THE T-TEACHERS' DEPARTMENT AND S-STOLE THE EXAM P-PAPER F-FOR YOU! #0 #8
... #1 #1 #- #4
..... #0 #7
....... #1 #1
......... #0 #7
........... #1 #1
........................................................... #0 #7
OH MY GOD THAT'S SO SWEET OF YOU! THANK YOU! #1 #3 #0 #-1
W-WELL YOU'RE WELCOME! #0 #10
(SHE CALLED ME SWEET!?!?!?) #0 #11
THIS WILL BE REALLY HELPFUL FOR MY BOYFRIEND! #1 #3 #- #- #0,5,-,-
(WAIT. BOYFRIEND?) #0 #6 #- #10 #2,1,93,2.5 #0,6,-,-
THANKS FOR THE HELP IDIOT #2 #0
(HE'S HER BOYFRIEND???? THE GUY WHO GOT AN YEAR BACK BECAUSE HE FAILED A SUBJECT???????) #0 #14
GOOD JOB MAKING HIM STEAL THE PAPER FOR ME LASYA #2 #0 #- #- #2,2,-,- #1,2,-,- #0,5,-,- 
COME NOW LET'S GO TO MY HOUSE FOR "GROUP STUDIES" #2 #1 #- #- #2,3,-,- 
HEHE, CAN'T WAIT! #1 #0 #- #- #2,0,99,4 #1,0,99,4
... #0 #14 #- #- #0,4,-,-
