...WHAT IS THAT? #0 #1
NO CLUE DA... #1 #0
OH WAIT, THAT'S THE ********** THAT THEY ****** FROM ****** TO ********* **********! I OVERHEARD SOME TEACHERS TALKING ABOUT IT! #1 #2
YOU CAN USE IT TO TELEPORT! YOU CAN EVEN TELEPORT THROUGH GLASS! #1 #1
BUT BE CAREFUL, TELEPORTING IS REALLY LOUD. #1 #0
