MACHA, IS THAT A BOOK? #1 #6
YEAH, I JUST FOUND IT HERE. #0 #0
MACHA I GOT ONE CRAZY IDEA! WHAT IF YOU TEAR ITS PAGES AND MAKE PAPER BALLS OUT OF THEM? #1 #2
YOU CAN THROW THEM, AND WHEN A TEACHER SEES ONE ON THE FLOOR THEY'LL GET DISTRACTED AND GO TO IT! #1 #2
WAIT, COULD THIS BE YOUR FIRST GOOD IDEA!? #0 #11
ALL MY IDEAS ARE GOOD REY IDIOT, YOU'RE JUST TOO DUMB TO UNDERSTAND. #1 #1
TO SELECT AN ITEM, USE THE 123 KEYS. YOU CAN ALSO USE THE SCROLL WHEEL OR JUST CLICK ON THE ITEM. #1 #5
PRESS SPACE TO USE THE SELECTED ITEM. #1 #5
YOU CAN USE THE BOOK TO TEAR PAGES AND MAKE PAPER BALLS. IT'S A BIG BOOK, SO YOU CAN TEAR AS MANY PAGES AS YOU WANT. #1 #5
BUT BE CAREFUL, TEACHERS MIGHT HEAR YOU TEARING PAGES. #1 #5
TO THROW A BALL, SELECT IT AND PRESS SPACE. #1 #5
AFTER THAT, MOVE THE MOUSE TO SELECT WHERE YOU WANT TO THROW IT AND THEN USE LEFT CLICK TO THROW. #1 #5