COME IN. COME IN, HQ. THIS IS PRABHU. OVER. #0 #0
WHAT HQ DA IT'S ME ONLY! #1 #0
AREY BRO, I WAS JUST TRYING TO ACT COOL. OVER. #0 #1
WHY DO YOU KEEP SAYING OVER BRO? WE JUST STARTED! #1 #0
AREY IT JUST MEANS THE MESSAGE IS OVER. #0 #1
IT MEANS THE MESSAGE IS WHAT? OVER. #1 #0
OKAY NOW YOU'RE DOING THIS ON PURPOSE. #0 #0
HAHA CHILL DA, CHUMMA I'M JOKING. #1 #2
DON'T JOKE BRO I HAVE TO STEAL THIS PAPER! #0 #1
MACHA IF YOU LIKE LASYA JUST GO TELL HER NO? WHY YOU'RE PUTTING SOME BIG SCENE STEALING PAPER AND ALL? #1 #0
BECAUSE I HAVE TO SHOW HER HOW COOL I AM! #0 #1
OKAY DA, JUST REMEMBER TO COME BACK HERE ONCE YOU GET THE PAPER. #1 #0
YOU WANT ME TO TELL YOU THE CONTROLS? #1 #0
WHAT CONTROLS? #0 #0
USE THE WASD KEYS TO MOVE. #1 #0
BRO WHAT DOES THAT EVEN MEAN? #0 #1
YOU'LL UNDERSTAND WHEN YOU'RE OLDER. #1 #0
BRO WHAT DO YOU MEAN? WE'RE THE SAME AGE! #0 #0
...HE HUNG UP. #0 #0
