COME IN. COME IN, HQ. THIS IS PRABHU. OVER. #0 #0
WHAT HQ DA IT'S ME ONLY! #1 #5
AREY BRO, I WAS JUST TRYING TO ACT COOL. OVER. #0 #3
WHY DO YOU KEEP SAYING OVER BRO? WE JUST STARTED! #1 #4
AREY IT JUST MEANS THE MESSAGE IS OVER. #0 #2
IT MEANS THE MESSAGE IS WHAT? OVER. #1 #5
OKAY NOW YOU'RE DOING THIS ON PURPOSE. #0 #4
HAHA CHILL DA, CHUMMA I'M JOKING. #1 #2
DON'T JOKE BRO THIS IS SERIOUS! #0 #5
MACHA IF YOU LIKE LASYA JUST GO TELL HER NO? WHY YOU'RE PUTTING SOME BIG SCENE STEALING EXAM PAPER AND ALL? #1 #5
BECAUSE I HAVE TO SHOW HER HOW COOL I AM! #0 #3
OKAY DA, JUST REMEMBER TO COME BACK HERE ONCE YOU GET THE PAPER. #1 #5
YOU WANT ME TO TELL YOU THE CONTROLS? #1 #5
WHAT CONTROLS? #0 #3
USE THE WASD KEYS TO MOVE. #1 #5
BRO WHAT DOES THAT EVEN MEAN? #0 #2
YOU'LL UNDERSTAND WHEN YOU'RE OLDER. #1 #1
BRO WHAT DO YOU MEAN? WE'RE THE SAME AGE! #0 #5
...HE HUNG UP. #0 #3
