DAMN BRO, THEY HAVE THOSE BIG OLD-STYLE CLOCKS! #0 #10
THEY'RE CALLED GRANDFATHER CLOCKS REY IDIOT. #1 #7
YOU CAN USE GRANDFATHER CLOCKS TO SAVE YOUR PROGRESS. #1 #5
ONCE YOU SAVE YOUR PROGRESS, IT'LL PERSIST EVEN IF YOU CLOSE THE GAME. #1 #5
YOU CAN ALSO CHANGE THE GAME'S DIFFICULTY AT GRANDFATHER CLOCKS. #1 #5
