TO SELECT AN ITEM, USE THE 123 KEYS. YOU CAN ALSO USE THE SCROLL WHEEL OR JUST CLICK ON THE ITEM. #1 #0
PRESS SPACE TO USE THE SELECTED ITEM. #1 #0
YOU CAN USE THE BOOK TO TEAR PAGES AND MAKE PAPER BALLS. IT'S A BIG BOOK, SO YOU CAN TEAR AS MANY PAGES AS YOU WANT. #1 #0
BUT BE CAREFUL, TEACHERS MIGHT HEAR YOU TEARING PAGES. #1 #0
TO THROW A BALL, SELECT IT AND PRESS SPACE. #1 #0
AFTER THAT, MOVE THE MOUSE TO SELECT WHERE YOU WANT TO THROW IT AND THEN USE LEFT CLICK TO THROW. #1 #0
