BRO THERE'S A TEACHER HERE! #0 #6
MACHA CAREFUL DA! IF HE SEES YOU, HE'LL TRY TO CATCH YOU AND IF HE CATCHES YOU, THEY'LL TAKE YOU TO THE PRINCIPAL! #1 #4
THEY CAN'T SEE YOU IF YOU'RE UNDER A TABLE, BUT IF THEY SEE YOU CRAWLING UNDER ONE, THEY CAN CROUCH TO LOOK UNDERNEATH. #1 #5
IF YOU CRAWL, YOU MOVE MORE SLOWLY, BUT IT'LL BE HARDER FOR THEM TO SEE YOU. #1 #5
THEY CAN EVEN HEAR YOUR FOOTSTEPS IF YOU'RE VERY CLOSE, BUT THEY CAN'T HEAR YOU IF YOU'RE CRAWLING. #1 #5
..... #0 #7
MACHA CAN YOU HEAR ME? #1 #5
............. #0 #7
WHAT DA? GOT SCARED AH? #1 #4
I-I'M NOT SCARED REY BUFFOON! #0 #8
MACHA YOU ONLY WANTED TO PUT ONE FULL SCENE TO IMPRESS LASYA! #1 #4
THIS IS YOUR FINAL CHANCE TO ABORT THE MISSION. YOU WON'T BE ABLE TO TURN BACK AFTER THIS. #1 #5
I'M NOT TURNING BACK. I DON'T KNOW HOW, BUT I'M GOING TO DO THIS. #0 #8
THEN GO DA. YOU HAVE MY SUPPORT. #1 #3
