YOU CAN USE GRANDFATHER CLOCKS TO SAVE YOUR PROGRESS. #1 #5
ONCE YOU SAVE YOUR PROGRESS, IT'LL PERSIST EVEN IF YOU CLOSE THE GAME. #1 #5
YOU CAN ALSO CHANGE THE GAME'S DIFFICULTY AT GRANDFATHER CLOCKS. #1 #5
