BRO, HOW DO I UNLOCK BLUE DOORS? #0 #2
...TAKE A WILD GUESS. #1 #7
ORANGE DOORS NEED ORANGE KEYS... SO DO I HAVE TO FIND A BLUE KEY? #0 #2
CONGRATS DA, YOU HAVE A BRAIN. TRY USING IT SOMETIMES. #1 #3
BRO I'M GOING TO SLAP YOU. #0 #5
