BRO, HOW DO I UNLOCK BLUE DOORS? #0 #0
...TAKE A WILD GUESS. #1 #0
ORANGE DOORS NEED ORANGE KEYS... SO DO I HAVE TO FIND A BLUE KEY? #0 #1
CONGRATS DA, YOU HAVE A BRAIN. TRY USING IT SOMETIMES. #1 #1
BRO I'M GOING TO SLAP YOU. #0 #0
