MACHA, THAT'S A LOCKED DOOR. #1 #5
YOU CAN UNLOCK A DOOR WITH A KEY OF THE SAME COLOUR. #1 #5
THIS DOOR NEEDS AN ORANGE KEY. #1 #5
OKAY BRO WHERE IS THE KEY? #0 #1
HOW SHOULD I KNOW DA? IT'LL BE THERE SOMEWHERE, YOU FIND IT. #1 #4