MACHA, THAT'S A LOCKED DOOR. #1 #0
YOU CAN UNLOCK A DOOR WITH A KEY OF THE SAME COLOUR. #1 #0
THIS DOOR NEEDS AN ORANGE KEY. #1 #0
OKAY BRO WHERE IS THE KEY? #0 #0
HOW SHOULD I KNOW DA? IT'LL BE THERE SOMEWHERE, YOU FIND IT. #1 #0