MACHA, TRY CRAWLING INTO THAT VENT OVER THERE! IN THE CORNER OF THE ROOM! #1 #1
WHY WOULD I DO THAT? #0 #1
IT'LL BE CRAZY DA! #1 #2
WHY DO I EVEN STILL TALK TO YOU... #0 #1
MACHA IT'S NOT LIKE YOU HAVE ANYWHERE ELSE YOU CAN GO. IF YOU'RE TOO SCARED TO GO THEN JUST SAY IT. #1 #1
I'M NOT SCARED! #0 #1
LIAR LIAR PANTS ON FIRE. #1 #1
I'LL CRAWL IN THERE AND SHOW YOU REY IDIOT! #0 #1
