A PURPLE DOOR, HUH? LOOKS LIKE I NEED A PURPLE KEY FOR IT... #0 #0
CRAZY DA, YOU FINALLY USED YOUR BRAIN ON YOUR OWN! #1 #1
THAT'S THE DOOR TO THE ROOM WHERE THEY STORE THE EXAM PAPERS. #1 #0
...THE PAPER IS BEHIND THIS DOOR, HUH? #0 #0
YEAH, IT IS. #1 #0
REMEMBER, YOU HAVE TO GET BACK TO THE ENTRANCE ONCE YOU GET THE PAPER. #1 #0
GOOD LUCK DA, I MEAN IT! #1 #0
