A PURPLE DOOR, HUH? LOOKS LIKE I NEED A PURPLE KEY FOR IT... #0 #1
CRAZY DA, YOU FINALLY USED YOUR BRAIN ON YOUR OWN! #1 #2
THAT'S THE DOOR TO THE ROOM WHERE THEY STORE THE EXAM PAPERS. #1 #5
...THE PAPER IS BEHIND THIS DOOR, HUH? #0 #2
YEAH, IT IS. #1 #5
REMEMBER, YOU HAVE TO GET BACK TO THE ENTRANCE ONCE YOU GET THE PAPER. #1 #5
GOOD LUCK DA, I MEAN IT! #1 #3
